services:

  mongo:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-admin123}
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server --maxmemory 200mb --maxmemory-policy allkeys-lru

  app:
    build: .
    restart: unless-stopped
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb://admin:admin123@mongo:27017/?authSource=admin}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-Nc/2vCmtlXcTNqY+ipCNp0DT6Gg}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET:-bKLIUw4cVhI6XyEJkhh030l3JaU}
      - URL_FRONTEND=${URL_FRONTEND:-http://localhost:8082}
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  mongo_data:
